# File: .azurepipelines/ci.yaml
#
# Description:
# This pipeline validates Rego policies using Open Policy Agent (OPA) and Conftest.
#

trigger: none
# trigger:
#   branches:
#     include:
#       - '*'

# pr:
#   branches:
#     include:
#       - main

resources:
  repositories:
    - repository: pipeline-library
      type: git
      name: Terraform-Governance-Center/pipeline-library
      ref: refs/heads/main

jobs:
  - job: ci
    displayName: OPA CI
    pool:
      vmImage: ubuntu-latest
    steps:
      - template: templates/lint.yaml
        parameters:
          policy_directory: policy

      - template: templates/test.yaml
        parameters:
          policy_directory: policy
          threshold: 90
          no_fail_test: 'false'
          no_fail_coverage: 'false'
